/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example cs@test.com */
                        email: string;
                        /** @example password */
                        password: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["LoginResponse"];
                401: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments, optionally filtered by status */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated sort fields. Prefix `-` for descending, no prefix for ascending. Example: `-created_at` (desc), `amount` (asc) */
                    sort?: components["parameters"]["sort"];
                    /** @description Filter by merchant name (case-insensitive partial match) */
                    search?: components["parameters"]["search"];
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["page"];
                    /** @description Number of items per page */
                    page_size?: components["parameters"]["page_size"];
                    /** @description Filter payments by status */
                    status?: "completed" | "processing" | "failed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["PaymentListResponse"];
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example unauthorized */
            code: string;
            /** @example missing or invalid token */
            message: string;
        };
        User: {
            /** @example cs@test.com */
            email?: string;
            /** @example cs */
            role?: string;
            /** @example eyJhbGci... */
            token?: string;
        };
        Payment: {
            /** @example 1 */
            id?: string;
            /** @example Tokopedia */
            merchant_name?: string;
            /** @example 150000 */
            amount?: string;
            /**
             * @example completed
             * @enum {string}
             */
            status?: "completed" | "processing" | "failed";
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description Successful login, returns JWT token and user info */
        LoginResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description List of payments with pagination metadata */
        PaymentListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    payments?: components["schemas"]["Payment"][];
                    /** @description Total number of matching payments */
                    total?: number;
                    /** @description Current page number */
                    page?: number;
                    /** @description Items per page */
                    page_size?: number;
                };
            };
        };
        /** @description Authentication failed or missing credentials */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Comma-separated sort fields. Prefix `-` for descending, no prefix for ascending. Example: `-created_at` (desc), `amount` (asc) */
        sort: string;
        /** @description Filter by merchant name (case-insensitive partial match) */
        search: string;
        /** @description Page number (1-indexed) */
        page: number;
        /** @description Number of items per page */
        page_size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
