// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCompleted  PaymentStatus = "completed"
	PaymentStatusFailed     PaymentStatus = "failed"
	PaymentStatusProcessing PaymentStatus = "processing"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusCompleted:
		return true
	case PaymentStatusFailed:
		return true
	case PaymentStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardV1PaymentsParamsStatus.
const (
	GetDashboardV1PaymentsParamsStatusCompleted  GetDashboardV1PaymentsParamsStatus = "completed"
	GetDashboardV1PaymentsParamsStatusFailed     GetDashboardV1PaymentsParamsStatus = "failed"
	GetDashboardV1PaymentsParamsStatusProcessing GetDashboardV1PaymentsParamsStatus = "processing"
)

// Valid indicates whether the value is a known member of the GetDashboardV1PaymentsParamsStatus enum.
func (e GetDashboardV1PaymentsParamsStatus) Valid() bool {
	switch e {
	case GetDashboardV1PaymentsParamsStatusCompleted:
		return true
	case GetDashboardV1PaymentsParamsStatusFailed:
		return true
	case GetDashboardV1PaymentsParamsStatusProcessing:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount       *string        `json:"amount,omitempty"`
	CreatedAt    *time.Time     `json:"created_at,omitempty"`
	Id           *string        `json:"id,omitempty"`
	MerchantName *string        `json:"merchant_name,omitempty"`
	Status       *PaymentStatus `json:"status,omitempty"`
}

// PaymentStatus defines model for Payment.Status.
type PaymentStatus string

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Sort defines model for sort.
type Sort = string

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Payments *[]Payment `json:"payments,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Prefix `-` for descending, no prefix for ascending. Example: `-created_at` (desc), `amount` (asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status Filter payments by status
	Status *GetDashboardV1PaymentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetDashboardV1PaymentsParamsStatus defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParamsStatus string

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email and password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List payments, optionally filtered by status
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email and password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List payments, optionally filtered by status
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xW32/bNhD+V4jbHlZAkZR1Awo9rVt/oEUHGGu6PmRGw0gnm61IqkcqrRbofx+OtC3J",
	"VpCs25Mt8n5833e8I2+htLq1Bo13UNxCK0lq9Ejhy1ny/FuhK0m1XlkDBfxmtZZnDtnWYyXYStQKm8ql",
	"YkVYq6/i6uxK1JYEe6KplNkkwljRxl3ekfuNVDz/KnXbYCGuzkpCjvlB+ivxAzs/SsSV1LYzvCBd+egv",
	"AwkoxvG5Q+ohASM1QhHBJuDKLWrJqDGGhQImYSEB37fB3pMyGxiGIQFC11rjMLB+YzfK/LFb4YXSGo8m",
	"KCHbtlGlZCWyj47luJ1k/J6whgK+y0ZRs7jrsncOKSabq/m2K0t0ru4a0XDiRBD6jowTr99fCG8/oRHS",
	"VKJzSEKZ2sKQwEr2Go1/o5z/JqAt2RbJK9wVPUQL/5VH7e7jskvPSHZiSiLZwzAu2OuPWPolwgxa2Foc",
	"sg4JvDOy81tL6m+snhNZegCbXXkD2C74o/FshFUg22ktqYcCflfOKbMRlvW7kY2qoqyQwI1sup1yFaPu",
	"JjggAY3OyQ1v6LtiBIIPOwGR2IIiT0fsyhpRS9Vgxan2WUvCig1k42DMF5gf1JqXNPKZ9sARtaMmmHCd",
	"Oum7pTvuIm6iz50iVv8y5h+Drk/OxeEMn2KP7T4Hcv5znuf5Eu5Jaxe3UFvS/A8q6fHMK41LPqo6ir4s",
	"CJVbafyHOF+m9hf2k22xUnLJz3npu0AETaejGOzng+4tWW53tk0gVprVGWNPjU81PlExjJUTCVFL1cwx",
	"l+4Xj86npdVLqMk2eOywZBfLPzPE/vX2+mWp0jR9CGaWCMuOlO/f8jmOiK9REhJ3wvj1Yl/M1+8v9pOd",
	"I8XdMdfW+zb2VZiPxS145QO0Zx0paVayF8+k215bSZV4unrFnY/kYvedp3maMzXbopGtggIep3n6mIsl",
	"/Tagy6q9e3ZznnEjZWFYB+WtC0eP9Q8N/KqCAlbW+UPOP8+ZWLhXIPYJOv+rrfr/MLT/fYlb6dwXS0dn",
	"/7B6X0vHhJMw68VhP7p46vD4bv0xz+8akwe7bH4BDwn8lJ/f73V6h0yPGhSX62RyKYQc4ovyWxGIhTv2",
	"QI095zWf3pEbXCj4S5zWe7U3T2ZPqstlEqNJFl4xQ3L85nqhGo90uDPFdS92c+aOx9B+c/Icevg0Oj4I",
	"62+p4tIb5X+r5XxgXK6HeXH5ibHXKhE2qCibphd10BGriYDxBke62Veoo2Y3VIosa2wpm611vniSP8lh",
	"WA//BAAA//8iXYlFMwsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
