// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCompleted  PaymentStatus = "completed"
	PaymentStatusFailed     PaymentStatus = "failed"
	PaymentStatusProcessing PaymentStatus = "processing"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusCompleted:
		return true
	case PaymentStatusFailed:
		return true
	case PaymentStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardV1PaymentsParamsStatus.
const (
	GetDashboardV1PaymentsParamsStatusCompleted  GetDashboardV1PaymentsParamsStatus = "completed"
	GetDashboardV1PaymentsParamsStatusFailed     GetDashboardV1PaymentsParamsStatus = "failed"
	GetDashboardV1PaymentsParamsStatusProcessing GetDashboardV1PaymentsParamsStatus = "processing"
)

// Valid indicates whether the value is a known member of the GetDashboardV1PaymentsParamsStatus enum.
func (e GetDashboardV1PaymentsParamsStatus) Valid() bool {
	switch e {
	case GetDashboardV1PaymentsParamsStatusCompleted:
		return true
	case GetDashboardV1PaymentsParamsStatusFailed:
		return true
	case GetDashboardV1PaymentsParamsStatusProcessing:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount       *string        `json:"amount,omitempty"`
	CreatedAt    *time.Time     `json:"created_at,omitempty"`
	Id           *string        `json:"id,omitempty"`
	MerchantName *string        `json:"merchant_name,omitempty"`
	Status       *PaymentStatus `json:"status,omitempty"`
}

// PaymentStatus defines model for Payment.Status.
type PaymentStatus string

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Page defines model for page.
type Page = int

// PageSize defines model for page_size.
type PageSize = int

// Search defines model for search.
type Search = string

// Sort defines model for sort.
type Sort = string

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	// Page Current page number
	Page *int `json:"page,omitempty"`

	// PageSize Items per page
	PageSize *int       `json:"page_size,omitempty"`
	Payments *[]Payment `json:"payments,omitempty"`

	// Total Total number of matching payments
	Total *int `json:"total,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Prefix `-` for descending, no prefix for ascending. Example: `-created_at` (desc), `amount` (asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Search Filter by merchant name (case-insensitive partial match)
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Page Page number (1-indexed)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Status Filter payments by status
	Status *GetDashboardV1PaymentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetDashboardV1PaymentsParamsStatus defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParamsStatus string

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email and password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List payments, optionally filtered by status
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email and password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List payments, optionally filtered by status
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xWS4/bNhD+KwTbQwJoLblpgUCnpnkhQVoYzaY5bI3sWBrZTERSGVKbVRb+78WQsi3b",
	"ctZNe9q1OI9vvnneycLqxho03sn8TjZAoNEj9b+WyH9LdAWpxitrZC5nsERhWr1AEg+mF8qUeIvlQ5lI",
	"xc+fW6ROJtKARplHG4l0xQo1RGMVtLWX+TSRWhmlWx3+913D8sp4XCLJ9ToJuh+c+joC4o/o31ZCedRO",
	"NEiid3UKRbQ0DiVLpIbbHkuW3YvMIVCxOob1QtUeSSw6oZGKFRgvGIF4UIDDC2UcGqe8ukHRAHkFtdDg",
	"i9Up8no3Q8x4C7qp+fHSfrINlgrkFqLzpMwyIrTkj/E9tVrDhUPOs8dSsJSoFNalm4gZYaVuxfXFtags",
	"CdZEUyqzTISxoomv/AKbh4l4HuHk4vqiIGSbH8Bfiwes/DAR16Bta/gDuOLh3+ZUnAx2PMqB2ZE414kk",
	"dI01DkPFvrFLZf7sv/CHwhqPJjABTVOrApiJ9KNjOu4GHn8krGQuf0h3DZHGV5e+cyHt6+SAzbdtUaBz",
	"VVuLmh0ngtC3ZJx4/f5SePsJjQBTitYhCWUqK9eJnEGn0fg3yvnvAtqQbZC8wm+06NOWCI0PHdG3qjyu",
	"42822KvDthrTDpEEHKEL7+OxD511e2tABF34bT3Uxygu+fNm2NgqdosyS7H1Pdqe/Se7+IiFH8scs8/2",
	"NmbEF+VXHKkygXeh0UMJHhjbOwOtX1lSX7F8TmTpjHz1BRwoaYM+Gs9CWIZ0tloDdTKXvyvnOCDLFXID",
	"tSpj4chE3kDd9rVRcjjtAIdMpEbnQvalPmUjRH5ejcfARqh6ssPOxFSgaizZ1cZrQViyANRO7vyFyLds",
	"7RdtjGfY5QehHbT5INahkj5N3fE8JPzcKmL2r6L/ndH5UcFsu/QYexxo+0Cmv2RZlo3hHgyv/E5WljT/",
	"J0vweOGVxjEdVR5YHyckrpcPcYKeuRcS6Tz4NgSChtfbVTgAavSB94YsDzSWTWTMNLOzsz0UPub4iMUw",
	"OI8oRA2q3sdcuF89Oj8prB5DTbbGQ4UxuZj+PUHsXq8WLws1mUzOwRx2e9GS8t1bruOIeIFASNwJu18v",
	"Nsl8/f5ys7vYUnzd+Vp538S+Chsgv5Ne+QDtWUsKzAw68QzcamGBSvFk9oo7H8nF7ptOsknGodkGDTRK",
	"5vLRJJs84mSBXwV0ablRT2+mKTdSGtZRYN66UHrMf2jgVyWfcNb5rc+/phxY2Jwy9gk6/5stu/+wlv59",
	"ihtw7oulg9rffr2vpaPDgZn56BbYqXhq8fB6+CnLTo3JrVy6f2KsE/lzNr1f63iHDEtN5lfzZLAUgo+4",
	"k0Jg4YrYhsaa+zkfbuIljiT8JQ7zPdstz+HBfzUexE4kDXfaOrlfLt6tZ0iG4+JMuXipsPDo0b3d5YtO",
	"9GPuxLW5eRzcm+cPw8M6nH9PEY0dgf9bKe3Pq6v5er+2+PTZcJUIG1iEuu5EFXjEckBgPCCQbjYF0lLd",
	"z7Q8TWtbQL2yzuePs8eZXM/X/wQAAP//MsBHWVAOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
